# command to run: docker-compose up

version: "3"

services:
  prod:
    image: vartanovs/ern-boilerplate
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: ["npm", "start"]

volumes:
  node_modules:
